Pagination
ForceAwakenz/Movies pull request #5
Opened 2021-11-01 09:11 UTC by ForceAwakenz

2021-11-01 09:22 UTC, LavrenovAlexey requested changes

2021-11-01 09:22 UTC, LavrenovAlexey commented on src/app/movies-list-view/movies/movies.component.ts
> +    private route: ActivatedRoute) {
activatedRoute должно называться

2021-11-01 09:22 UTC, LavrenovAlexey commented on src/app/movies-list-view/movies/movies.component.ts
> +    this.route.queryParams.subscribe((params: Params) => {
subscribe в subscribe звучит плохо

почитай про switchMap и используй его тут

+ нужно использовать takeUntil

+ плохо, что это так написано в ngOninit должно быть как отдельный метод и этот метод уже вызваться в ngOnInit 

+ так же хочу отметить, что информацию о фильмах мы теперь должны получать в компоненте на уровень выше, а не тут

2021-11-01 09:22 UTC, LavrenovAlexey commented on src/app/shared/services/movie-data.service.ts
> +    let searchParams = new HttpParams()
как ты видишь куча дублирования кода  с переменной searchParams, можно явно упростить

но за идею сделать так + в карму

2021-11-01 09:22 UTC, LavrenovAlexey commented on src/app/shared/services/movie-data.service.ts
> +  getPagesTotal(): Observable<number> {
зачем делать лишний запрос на получения тотала? делаешь лишний запрос

2021-11-01 09:22 UTC, LavrenovAlexey commented on src/app/movies-list-view/paginator/paginator.component.html
> +                [queryParams]="{ page: 1}">
плохо, ибо ты опять добавляешь частную логику в компоненту, когда компонента вообще об этом не должна знать

эта компонента должна отвечать только за отображение пагинации правильно, но никак не должна отвечать за то, что именно должно происходить по клику

2021-11-01 09:22 UTC, LavrenovAlexey commented on src/app/movies-list-view/paginator/paginator.component.ts
> +  ngOnInit() {
всю инфу, которую ты получаешься получить внутри этого хука, эта компонента должна получать из вне

2021-11-01 09:44 UTC, ForceAwakenz commented on src/app/movies-list-view/movies/movies.component.ts
> +    private route: ActivatedRoute) {
сделал

2021-11-01 10:16 UTC, ForceAwakenz commented on src/app/shared/services/movie-data.service.ts
> +    let searchParams = new HttpParams()
Cделал апи кей базовым свойством парамс, потому что оно будет использоваться при каждом запросе и вынес все это в свойство класса.

2021-11-01 16:20 UTC, ForceAwakenz commented on src/app/shared/services/movie-data.service.ts
> +  getPagesTotal(): Observable<number> {
исправил

2021-11-01 16:20 UTC, ForceAwakenz commented on src/app/movies-list-view/paginator/paginator.component.html
> +                [queryParams]="{ page: 1}">
Исправил

2021-11-01 16:20 UTC, ForceAwakenz commented on src/app/movies-list-view/paginator/paginator.component.ts
> +  ngOnInit() {
Исправил

2021-11-04 19:57 UTC, ForceAwakenz commented on src/app/movies-list-view/movies/movies.component.ts
> +    this.route.queryParams.subscribe((params: Params) => {
сделал все, кроме takeUntil, не наше, куда его прикрутить)

2021-11-05 16:26 UTC, LavrenovAlexey approved these changes

2021-11-05 17:07 UTC, merged